configfile: "../config.yaml"

biosamples_accessions = "aac.00483-19-s0001.csv"
metadata_dir = "biosamples_metadata"

rule all:
    input:
        config["samples_dir"]+"/.moved_completed",
        "amr_labels.csv"

rule get_assembly_accession_ids:
    input:
        biosamples_accessions
    output:
        "assembly_accession_ids.txt"
    conda:
        "envs/ncbi.yaml"
    shell:
        """
        bash scripts/get_assembly_accession_ids.sh {input} {output}
        """

rule get_biosamples_metadata:
    input:
        biosamples_accessions
    output:
        directory(metadata_dir)+f"/.metadata_completed"
    conda:
        "envs/ncbi.yaml"
    shell:
        """
        bash scripts/get_biosamples_metadata.sh {input} {metadata_dir}
        touch {output}
        """

rule get_amr_labels:
    input:
        metadata_dir+f"/.metadata_completed"
    output:
        "amr_labels.csv"
    conda:
        "envs/parsing.yaml"
    shell:
        """
        python scripts/get_amr_labels.py --biosamples-summary-dir {metadata_dir} --output {output}
        """

rule download_assemblies:
    input:
        "assembly_accession_ids.txt"
    output:
        temp("ncbi_dataset.zip")
    conda:
        "envs/ncbi.yaml"
    shell:
        "datasets download genome accession --inputfile {input} --filename {output}"

rule unzip_assemblies:
    input:
        "ncbi_dataset.zip"
    output:
        directory("ncbi")
    shell:
        "unzip {input} -d {output}"

rule move_fasta_files:
    input:
        "ncbi"
    output:
        directory(config["samples_dir"])+"/.moved_completed"
    shell:
        """
        find {input}/ncbi_dataset/data/ -maxdepth 2 -iname "*.fna" -print0 | xargs -0 -I {{}} mv -v "{{}}" {config[samples_dir]}/
        touch {output}
        """